### ISSUE TITLE
How to change the color/size/shape of edges/nodes?

### ISSUE THREAD

**Issue by karinsasaki** [scikit-tda/kepler-mapper#132]
Is it possible to specify parameters for color, size and shape of both the edges and the nodes of the graphs, using either or both plotlyviz or visualize (that generates the html file) functions?

(I know it is possible to change the color of the nodes, but I do knot know if any of the other things are possible.)

Looking at the source code of [visuals](https://github.com/MLWave/kepler-mapper/blob/master/kmapper/visuals.py), it seems these things are predefined (see below) and can not be changed (unless the source code itself is changed) - is this correct? 

```
def _size_node(member_ids):
    return int(np.log(len(member_ids) + 1) + 1)

def _type_node():
    return "circle"

def _size_link_width(graph, node_id, linked_node_id):
    return 1
```

Thanks!

**Comment by sauln** [comment]
Currently that is the case. We are open to PR if you’d like to add those customizations.

**Comment by empet** [comment]
@karinsasaki   You can update the Plotly `FigureWidget` to perform the desired attribute changes, as in this Jupyter Notebook: [https://nbviewer.jupyter.org/gist/empet/bdb436db9cfd2b75de1e81b60b9d9869](https://nbviewer.jupyter.org/gist/empet/bdb436db9cfd2b75de1e81b60b9d9869).

**Comment by karinsasaki** [comment]
@empet this is great! Thank you!

@sauln I can give it a go - i'll come back to you when I do!

**Comment by kaitai** [comment]
Hello -- I'm commenting here as the title is descriptive of my issue although I think this is a bit different. I would like to change the sizes of the edges based on the percent overlap of the cluster. (We can specify overlap of intervals in the Mapper parameters, but this doesn't quite correspond to number of shared members of cluster.) I'd like to scale edge thicknesses by (# elements of intersection)/(# elements of union).

I cannot figure out how to do this with Plotly! I can't quite figure it out using D3 either. 

I have tried modifying nominal_stroke in kmapper.js, and the .style("stroke-width", function(d) { return d.w * nominal_stroke; }) tag in kmapper.js (somewhere around line 142 in kmapper.js). This has no effect.

In plotlyviz.py, I've tried changing "weight" in the scomplex_to_graph function, adding the following in the "weight" line (around line 247 in the plotlyviz.py file). 

`    for i, (node_id, linked_node_ids) in enumerate(simplicial_complex["links"].items()):
        for linked_node_id in linked_node_ids:
            lnk = {
                "source": node_id_to_num[node_id],
                "target": node_id_to_num[linked_node_id],
                "weight": size_link_width(simplicial_complex, node_id, linked_node_id)
            }

            json_dict["links"].append(lnk)`

This uses function 
`
def size_link_width(graph, node_id, linked_node_id):
    return math.ceil(100*len(set(graph['nodes'][node_id]).intersection(graph['nodes'][linked_node_id]))/len(set(graph['nodes'][node_id]).union(graph['nodes'][linked_node_id])))
`

One 

I can't figure edge width out with NetworkX, either, but there it is easy to scale edge color instead to get an analogous visualization. In NetworkX you can just zip together edges and attributes and color away:
`G = nx_graph
for u,v,d in G.edges(data=True):
    d['weight'] = math.ceil(100*len(set(scomplex['nodes'][u]).intersection(scomplex['nodes'][v]))/len(set(scomplex['nodes'][u]).union(scomplex['nodes'][v])))


edges,weights = zip(*nx.get_edge_attributes(G,'weight').items())

#pos = nx.spring_layout(G)
nx.draw(G, node_color='b', node_size = 0.1, edgelist=edges, edge_color=weights, width=1.0, edge_cmap=plt.cm.Reds)

plt.savefig("testing123.pdf")`

Since it's possible to modify edge colors in NetworkX, I thought it would also be possible in Plotly. Thus I conclude I'm trying to modify the wrong thing in the kepler-mapper visualization flow. Any suggestions?
