### ISSUE TITLE
Fixing the plot. 

### ISSUE THREAD

**Issue by pdlotko** [scikit-tda/kepler-mapper#187]
Dear All,
Is there a possibility to fix the Kepler Mapper graphs so that any time I re-open the html file, I will get the same shape of the graph?
all the best
pawel

**Comment by MLWave** [comment]
Not at the moment. The shape / orientation is random and relies on D3.js force-directed graph for the layout.

As for a fix, this seems difficult for me. It is perhaps possible to fix nodes in the force-directed graph, or write custom code to always create the same shape, but for me, that would be hard.

**Comment by deargle** [comment]
When I get to it, I think I can swing persisting graph position across
reloads, using browser local storage. Initial node position can be set, see
https://bl.ocks.org/mbostock/3750558

As for the positioning persisting across browsers, I'd have to think about
that one, but probably also doable via json field copy paste export import
of node positions.

**Comment by pdlotko** [comment]
Dear Both,
thanks for answer. The reason I have asked this question is that often, for papers in particular, one need to plot a few mapper graphs with different coloring functions. It is then essential to keep the same shape of the mapper graph.
I have developed an algorithm that is similar in spirit to mapper. In the R implementation, in addition to the dynamics graphs, I am having a static graphs exactly for that purpose. It is not as fun as the dynamic one, but it serves the purpose. 
As, in my oppinion, you have the best publicially available version of mapper, I would strongly suggest building something like this. If you wish I can look a the options and send you a suggestion. Just let me know,
all the best
pawel

**Comment by sauln** [comment]
Hi Pawal,  in this scenario, we supply a converter to networkx. It’s not dynamic, but can render plots nicely.

If you have ideas of improving the static capability, please do let us know.

**Comment by deargle** [comment]
for the information of everyone, I'm working on "saving" d3 plot positions. After that, I'll work on custom color functions.

**Comment by sauln** [comment]
That's very exciting! I know that would solve a long standing pain point of the visualizations 💯

**Comment by pdlotko** [comment]
Great news, I will check it out ASAP!
Thank you so much,
all the best
pawel

śr., 26 sie 2020 o 18:32 Nathaniel Saul <notifications@github.com>
napisał(a):

**Comment by deargle** [comment]
Thinking through this out loud. Basic need will be to "save" the positions and fixed-states of all of the nodes. Thinking about doing things in this order:
* enable "fixing" the position of a single node. I've done this before where any node that is dragged becomes "fixed"
* a key to "fix" the position of _all_ nodes on the screen, and a key to unfix all
* "saving" of current node positions. this is tricky. I do not think that we can do constant saving of the state to local storage, for logistics reasons. if constantly saving, what would happen if two tabs open a file at the same time? collisions. I think we need to have a button (key?) that saves state, and one that loads state. 
   - save where? to local storage is good, but also need a way to export and load from, like, a downloaded text file so that it can be run elsewhere

**Comment by sauln** [comment]
I think there are a couple main user stories we should be focused on

_I arrange the graph how I like and then change the colors to view a different function_

_I arrange the graph how I like and then I want to share it with someone else_

Localstorage could help with the first one, but I don't think it will work for sharing or for revisiting a graph later.  It would be great if the layout could be somehow saved with the html file.  Maybe we can resave it?

This is definitely a tricky problem.

**Comment by deargle** [comment]
Having a webpage save a modified version of itself? Ayy! I guess it's possible. That _would_ keep things to a single file... you know what, I bet it's entirely possible. 

What's your thought though on saving a positioning config to a textfile that could be distributed along with the html file, and loaded via a button and file-selection? Too much friction from having two files to pass around?

**Comment by sauln** [comment]
I think the separate config could work very well! It imagine a button that lets you export and import the config, or alternatively, export a whole new html file.

It’s definitely a weird pattern.. i don’t know if there are any great ways to solve it with the tools we have.

**Comment by deargle** [comment]
@sauln you okay with a major version bump for all these vis changes? Breaking api.

I want `format_mapper_data` to not return _any_ html -- rather, just data -- that javascript in the html file is responsible for rendering. This should:
* help make `visuals.py` generalizable to other vis approaches such as `plotlyviz` with less code duplication
* reduce filesize a bit
* do MVC a bit better, separate the data from its presentation
* etc

But would require changing what `format_mapper_data` returns. Currently, it returns some html because it pre-renders tooltip html. Also would mean ignoring any `env` argument passed to that function. Latter wouldn't necessarily be breaking, but former could, if someone relies on `format_mapper_data` to return html for the tooltips (tacky, perish the thought).

**Comment by deargle** [comment]
I guess we could avoid a break and return _both_ the straight tooltip data and _also_ the html... gross, but...

**Comment by sauln** [comment]
I'm okay with a major version bump.. this viz improvement would be a pretty big deal for the project.

**Comment by deargle** [comment]
d3 plot always draws the same in #196 

In that PR there's also the ability to drag things about and save and load that config

**Comment by sauln** [comment]
Sweet! Is it ready for review?

**Comment by deargle** [comment]
mmm yeah I'd say so. I'm doing minutiae other things now to the html, but the python needs your eye. I'm sure I've done some unconventional things. If you have time to review it now, I can try to answer questions in real time on the PR.

**Comment by sauln** [comment]
I don't have time right now, but I'll try to get to take a look this weekend.

**Comment by deargle** [comment]
Closed by v2 release
